org: campodonico
app: apigestionarchivos
service: apigestionarchivos

frameworkVersion: '2'

custom:
  wsgi:
    app: app.app

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: '20201221'
  region: us-east-2

functions:
  api:
    handler: wsgi_handler.handler
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{proxy+}
          method: ANY

plugins:
  - serverless-wsgi
  - serverless-python-requirements
